---
vagrantfile-rackspace:
    vm:
        box: rackspace
        hostname: master
        provider:
            rackspace:
                server_name: PuPHPet
                image: Wheezy
                region: dfw
                size: '2 GB Performance'
                username: xxxx
                api_key: xxxx
        provision:
            puppet:
                manifests_path: puphpet/puppet
                manifest_file: manifest.pp
                options:
                    - '--verbose'
                    - '--hiera_config /vagrant/puphpet/puppet/hiera.yaml'
                    - '--parser future'
        synced_folder:
            sA0hn1dDNuar:
                id: webroot
                source: ~/www/puphpet/ssl
                target: /etc/ssl/certs/puphpet.com/
    ssh:
        host: null
        port: null
        private_key_path: ~/.ssh/id_rsa
        public_key_path: ~/.ssh/id_rsa.pub
        username: xxxxx
        guest_port: null
        keep_alive: true
        forward_agent: false
        forward_x11: false
        shell: 'bash -l'
    vagrant:
        host: detect
server:
    packages:
        - vim
        - htop
        - curl
        - libgdbm3
        - wget
        - zip
    dot_files:
        -
            bash_aliases: null
    _prevent_empty: ''
mailcatcher:
    install: 0
    settings:
        smtp_ip: 0.0.0.0
        smtp_port: 1025
        http_ip: 0.0.0.0
        http_port: '1080'
        mailcatcher_path: /usr/local/bin
        log_path: /var/log/mailcatcher/mailcatcher.log
apache:
    install: '1'
    settings:
        user: www-data
        group: www-data
        default_vhost: true
        manage_user: false
        manage_group: false
        sendfile: 0
    modules:
        - php
        - rewrite
    vhosts:
        yivniinvinvr:
            servername: puphpet.com
            serveraliases:
                - www.puphpet.com
            docroot: /var/www/puphpet.com/public_html/web
            port: '80'
            override:
                - All
            custom_fragment: 'Redirect permanent / https://puphpet.com/'
            ssl_cert: ''
            ssl_key: ''
            ssl_chain: ''
            ssl_certs_dir: ''
        ZuCEoYDoH6T7:
            servername: puphpet.com
            serveraliases:
                - www.puphpet.com
            docroot: /var/www/puphpet.com/public_html/web
            port: '443'
            override:
                - All
            custom_fragment: 'DirectoryIndex app.php'
            ssl: '1'
            ssl_cert: /etc/ssl/certs/puphpet.com/puphpet_com.crt
            ssl_key: /etc/ssl/certs/puphpet.com/apache2.key
            ssl_chain: /etc/ssl/certs/puphpet.com/PositiveSSLCA2.crt
            ssl_certs_dir: ''
        xjZ44FQnZ5l9:
            servername: box.puphpet.com
            serveraliases:
                - www.box.puphpet.com
            docroot: /var/www/box.puphpet.com/public_html/
            port: '80'
            override:
                - All
            custom_fragment: ''
            ssl_cert: ''
            ssl_key: ''
            ssl_chain: ''
            ssl_certs_dir: ''
    mod_pagespeed: 0
    mod_spdy: 0
nginx:
    install: 0
    vhosts:
        sZWyznjBNGYE:
            server_name: awesome.dev
            server_aliases:
                - www.awesome.dev
            www_root: /var/www/awesome.dev
            listen_port: '80'
            index_files:
                - index.html
                - index.htm
                - index.php
            envvars:
                - 'APP_ENV dev'
php:
    install: '1'
    version: '55'
    composer: '1'
    modules:
        php:
            - cli
            - intl
            - mcrypt
            - curl
        pear: {  }
        pecl:
            - pecl_http
    ini:
        session.save_path: /var/lib/php/session
    timezone: America/Chicago
xdebug:
    install: 0
    settings:
        xdebug.default_enable: '1'
        xdebug.remote_autostart: '0'
        xdebug.remote_connect_back: '1'
        xdebug.remote_enable: '1'
        xdebug.remote_handler: dbgp
        xdebug.remote_port: '9000'
drush:
    install: 0
    settings:
        drush.tag_branch: 6.x
mysql:
    install: 0
    root_password: '123'
    phpmyadmin: 0
    adminer: 0
    databases:
        Hw0yc2SwNcup:
            grant:
                - ALL
            name: dbname
            host: localhost
            user: dbuser
            password: '123'
            sql_file: ''
postgresql:
    install: 0
    settings:
        root_password: '123'
        user_group: postgres
        encoding: UTF8
        version: '9.3'
    databases: {  }
    adminer: 0
mariadb:
    install: 0
    root_password: '123'
    phpmyadmin: 0
    adminer: 0
    databases: {  }
    version: '10.0'
mongodb:
    install: 0
    settings:
        auth: 1
        port: '27017'
    databases: {  }
redis:
    install: 0
    settings:
        conf_port: '6379'
beanstalkd:
    install: 0
    settings:
        listenaddress: 0.0.0.0
        listenport: '13000'
        maxjobsize: '65535'
        maxconnections: '1024'
        binlogdir: /var/lib/beanstalkd/binlog
        binlogfsync: null
        binlogsize: '10485760'
    beanstalk_console: 0
    binlogdir: /var/lib/beanstalkd/binlog
rabbitmq:
    install: 0
    settings:
        port: '5672'

